apiVersion: v1
kind: ConfigMap
metadata:
  name: splitwise-config
  namespace: splitwise
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: splitwise_db
  NODE_ENV: production
  PORT: "5000"
